name: E2E - Playwright

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ secrets.ALLURE_ENDPOINT }}
          allure-project-id: ${{ secrets.ALLURE_PROJECT_ID }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}

      - name: Run Playwright tests (with Allure upload)
        run: allurectl watch --results allure-results -- npm run test:e2e
        env:
          CI: 'true'

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/**/trace.zip
          if-no-files-found: ignore

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: ignore

      # Optional: Publish Allure to GitHub Pages (local report)
      # - name: Generate Allure static report
      #   if: always()
      #   run: |
      #     npx allure-commandline generate --clean allure-results -o allure-report
      #
      # - name: Upload Allure report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-report
      #     path: allure-report
      #     if-no-files-found: ignore

      # Upload to Allure TestOps handled by allurectl watch
